/**
 * Copyright (C) 2011 WRML.org <mark@wrml.org>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.wrml;

import java.lang.reflect.TypeVariable;
import java.net.URI;
import java.util.HashMap;
import java.util.Map;
import java.util.SortedMap;
import java.util.TreeMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.wrml.model.communication.http.MediaType;
import org.wrml.model.schema.Schema;
import org.wrml.model.schema.TextSyntaxConstraint;
import org.wrml.service.CachingService;
import org.wrml.service.Service;
import org.wrml.service.WebClient;
import org.wrml.service.runtime.SchemaService;
import org.wrml.service.runtime.SystemSchemaService;
import org.wrml.util.CachingTransformer;
import org.wrml.util.DelegatingObservableMap;
import org.wrml.util.ObservableMap;
import org.wrml.util.StringTransformer;
import org.wrml.util.Transformer;
import org.wrml.util.UriTransformer;

/**
 * 
 * Thread Dimension (Runtime Thread Local)
 * 
 * TODO: Consider making Context have a global static AND a thread local
 * instance, the latter of which takes hierarchically "scoped" precedence
 * over the former.
 * 
 * This will allow for the Context to be read "globally" within a scope that
 * makes logical sense in multithreaded programs, like an web resource
 * server.
 * 
 * That being said, by handing each Model its own Context there is the
 * opportunity to create some very fine-grained scopes using context
 * implementations, meaning that the thread local scope may be different but
 * "parented" by the global context.
 * 
 * Reference Dimension (Design-time Composition)
 * 
 * Parenting means making contexts hierarchical using object references,
 * meaning that a context could have a parent and children. On the server
 * side this might be used relate the thread local context to the parent
 * context, even to the point of the child delegating (cascading) to the
 * parent reference for a default value or behavior that doesn't need to be
 * overridden locally.
 * 
 * This hierarchy can also be a useful abstraction when building
 * applications such as user interfaces, which may have nested contexts for
 * data and associated actions (e.g. plug-ins). In these situations the
 * thread local may not be an effective slot to achieve context locality.
 * 
 * Polymorphism Dimension (Design-time Inheritance)
 * 
 * Context subclasses can alter the default behavior and values by
 * overriding certain methods (and obviously by implementing the absract
 * ones).
 * 
 * TODO: Eventually need to figure out how to make LinkRelation and other
 * core types extend Model. This is the dog food that WRML must eat in
 * order to use itself to make itself (bootstrap).
 * 
 * This will allow WRML to treat these core type instance "loadings" just
 * like any other application using WRML. Meaning that there is an
 * associated service class for each core type. This association can be
 * formed at program start-up (via config/wiring) which results in a
 * registration by schema within the Context. The mapping can be changed as
 * needed at runtime. The type registration can be repeated for the same
 * service and may also include simple URI wildcard patterns to allow for a
 * single service to handle many schema types. For example an API that
 * stores schema instances in a flexible document store (e.g. mongoDB) could
 * handle requests for many different schema types and CRUD them with ease.
 * 
 * For the Java implementation of WRML to leverage itself (bootstrap), for
 * its own core APIs and tools, all core WRML classes must be stripped down
 * to interfaces, with all of their implementation responsibilities shifted
 * to the framework. This is what it will take to be a truly web resource
 * model-oriented, metadata-driven application framework.
 * 
 * For starters we could use Java interface definitions as placeholders for
 * these core types schema's being accessible via the schema REST API. Hand
 * coding the interface with a mindset of auto-generation, meaning simple
 * repeatable patterns for method signatures and that reference types that
 * can themselves be easily generated and fetched. This will allow these
 * interfaces to later be generated by code that is built into the runtime
 * and compile time environments to allow the eventual web based schemas to
 * be coded against directly.
 * 
 * The impl subclasses could be instantiated using a Proxy class that calls
 * the Model's getFieldValue or Link.click. This drives all
 * implementation concerns down into the framework's Model, its Links,
 * and the supporting Context. With the Context providing hooks for
 * application code.
 * 
 * This Proxy approach may prove to be the final solution or we may decide
 * to auto-generate impl classes via our own code generation.
 */
public class Context {

    private static final String WRML_MEDIA_TYPE = "application/wrml";
    private static final String MEDIA_TYPE_REGEX_STRING = "^" + "([a-zA-Z0-9!#$%^&\\*_\\-\\+{}\\|'.`~]+)/"
            + "([a-zA-Z0-9!#$%^&\\*_\\-\\+{}\\|'.`~]+)( +" + "([a-zA-Z0-9!#$%^&\\*_\\-\\+{}\\|'.`~]+)=\"([^\"]*)\";)*$";

    private static final Pattern MEDIA_TYPE_REGEX_PATTERN = Pattern.compile(MEDIA_TYPE_REGEX_STRING);

    private final ObservableMap<URI, Service> _ServiceMap;
    private final ObservableMap<URI, Prototype> _Prototypes;

    private SchemaService _SchemaService;
    private CachingService _SchemaCachingService;

    private Transformer<MediaType, String> _MediaTypeToStringTransformer;
    private Transformer<MediaType, Class<?>> _MediaTypeToClassTransformer;
    private Transformer<MediaType, URI> _MediaTypeToSchemaIdTransformer;

    public Context() {
        _ServiceMap = new DelegatingObservableMap<URI, Service>(new HashMap<URI, Service>());
        _Prototypes = new DelegatingObservableMap<URI, Prototype>(new HashMap<URI, Prototype>());

        SchemaService schemaService = new SystemSchemaService(this, new WebClient(this));
        setSchemaService(schemaService);

        Transformer<MediaType, String> mediaTypeToStringTransformer = new CachingTransformer<MediaType, String, Transformer<MediaType, String>>(
                new MediaTypeToStringTransformer());
        setMediaTypeToStringTransformer(mediaTypeToStringTransformer);

        Transformer<MediaType, Class<?>> mediaTypeToClassTransformer = new CachingTransformer<MediaType, Class<?>, Transformer<MediaType, Class<?>>>(
                new MediaTypeToClassTransformer());

        setMediaTypeToClassTransformer(mediaTypeToClassTransformer);

        Transformer<MediaType, URI> mediaTypeToSchemaIdTransformer = new CachingTransformer<MediaType, URI, Transformer<MediaType, URI>>(
                new MediaTypeToSchemaIdTransformer());

        setMediaTypeToSchemaIdTransformer(mediaTypeToSchemaIdTransformer);
    }

    public String getClassName(URI schemaId) {
        UriTransformer<?> schemaIdTransformer = _SchemaService.getIdTransformer();
        return (String) schemaIdTransformer.aToB(schemaId);
    }

    /*
     * TODO: Consider moving all of this voodoo to the SchemaService interface.
     * Keep this class more universally useful to all apss - not just the
     * bootstrapping of the WRML runtime "app".
     */

    public Transformer<MediaType, Class<?>> getMediaTypeToClassTransformer() {
        return _MediaTypeToClassTransformer;
    }

    public Transformer<MediaType, URI> getMediaTypeToSchemaIdTransformer() {
        return _MediaTypeToSchemaIdTransformer;
    }

    public Transformer<MediaType, String> getMediaTypeToStringTransformer() {
        return _MediaTypeToStringTransformer;
    }

    public Prototype getPrototype(URI blueprintSchemaId) {

        if (!_Prototypes.containsKey(blueprintSchemaId)) {
            Prototype prototype = new Prototype(this, blueprintSchemaId);
            _Prototypes.put(blueprintSchemaId, prototype);
        }

        return _Prototypes.get(blueprintSchemaId);
    }

    public Schema getSchema(URI schemaId) {
        return (Schema) _SchemaCachingService.get(schemaId);
    }

    public URI getSchemaId(Class<?> clazz) {
        return getSchemaId(clazz.getCanonicalName());
    }

    public URI getSchemaId(String className) {
        @SuppressWarnings("unchecked")
        UriTransformer<String> schemaIdTransformer = (UriTransformer<String>) _SchemaService.getIdTransformer();
        return schemaIdTransformer.bToA(className);
    }

    public SchemaService getSchemaService() {
        return _SchemaService;
    }

    public Service getService(Class<?> clazz) {
        URI schemaId = getSchemaId(clazz);
        return getService(schemaId);
    }

    public Service getService(String className) {
        URI schemaId = getSchemaId(className);
        return getService(schemaId);
    }

    public Service getService(URI schemaId) {

        /*
         * TODO: Allow for more complex mapping of schemas to services
         * For example, allow for a base schema to be registered for
         * sub-services or a uri pattern match.
         */

        return _ServiceMap.get(schemaId);
    }

    public ObservableMap<URI, Service> getServiceMap() {
        return _ServiceMap;
    }

    public StringTransformer<?> getStringTransformer(TextSyntaxConstraint textSyntaxConstraint) {
        // TODO: Implement this mapping with configuration-based mapping falling back to code on demand
        return null;

    }

    public CachingService instantiateCachingService(Service originService) {
        final Map<URI, Model> rawModelMap = new HashMap<URI, Model>();
        final ObservableMap<URI, Model> observableModelCache = new DelegatingObservableMap<URI, Model>(rawModelMap);
        return new CachingService(this, originService, observableModelCache);
    }

    public Model instantiateModel(Class<?> schemaClass) {
        final URI schemaId = getSchemaId(schemaClass);
        return instantiateModel(schemaId);
    }

    public Model instantiateModel(URI schemaId) {
        RuntimeModel model = new RuntimeModel(schemaId, this);
        return model;
    }

    public void setMediaTypeToClassTransformer(Transformer<MediaType, Class<?>> mediaTypeToClassTransformer) {
        _MediaTypeToClassTransformer = mediaTypeToClassTransformer;
    }

    public void setMediaTypeToSchemaIdTransformer(Transformer<MediaType, URI> mediaTypeToSchemaIdTransformer) {
        _MediaTypeToSchemaIdTransformer = mediaTypeToSchemaIdTransformer;
    }

    public void setMediaTypeToStringTransformer(Transformer<MediaType, String> mediaTypeToStringTransformer) {
        _MediaTypeToStringTransformer = mediaTypeToStringTransformer;
    }

    public void setSchemaService(SchemaService schemaService) {

        _SchemaService = schemaService;
        _SchemaCachingService = instantiateCachingService(schemaService);
        URI schemaSchemaId = getSchemaId(Schema.class);
        _ServiceMap.put(schemaSchemaId, _SchemaCachingService);
    }

    private final class MediaTypeToClassTransformer extends MediaTypeTransformer<Class<?>> {

        public Class<?> aToB(MediaType bValue) {
            // TODO Auto-generated method stub
            return null;
        }

        public MediaType bToA(Class<?> clazz) {

            if (clazz == null) {
                return null;
            }

            MediaType mediaType = null;
            Transformer<MediaType, String> mediaTypeToStringTransformer = getContext()
                    .getMediaTypeToStringTransformer();

            if (clazz.isAssignableFrom(Model.class)) {

                if (clazz.equals(Model.class)) {

                    // Return the vanilla application/wrml type for base models                    
                    return mediaTypeToStringTransformer.bToA(WRML_MEDIA_TYPE);
                }
                else {
                    // Return the application/wrml with schema param for derived models
                    URI schemaId = getSchemaId(clazz);

                    // TODO: Allow for parameterized types via Constraints
                    SortedMap<String, URI> schemaConstraints = null;

                    /*
                     * Use reflection to determine if the type is parameterized.
                     * Ultimately
                     * looking to get a map of type parameter name (aka Schema
                     * Constraint Name)
                     * to schema Id. Get the name (keys) from the Java generics
                     * reflection API.
                     * Get the URI values using Java class name to Schema URI
                     * transform.
                     * 
                     * TODO: Need to figure out how to get a Java generic
                     * interface's
                     * parameterized type names and actual types (as a Model
                     * subclass)
                     * 
                     * http://www.artima.com/weblogs/viewpost.jsp?thread=208860
                     */

                    TypeVariable<?>[] typeParameters = clazz.getTypeParameters();
                    if (typeParameters != null) {
                        schemaConstraints = new TreeMap<String, URI>();
                        for (TypeVariable<?> typeParam : typeParameters) {
                            String name = typeParam.getName();

                            Class<?> typeParamSchemaClass = null;
                            URI typeParamSchemaId = getSchemaId(typeParamSchemaClass);
                            schemaConstraints.put(name, typeParamSchemaId);
                        }
                    }

                    final StringBuilder sb = new StringBuilder();
                    sb.append(WRML_MEDIA_TYPE);

                    // TODO: Append params

                    mediaType = mediaTypeToStringTransformer.bToA(sb.toString());
                }
            }
            else {
                // TODO: Get MediaType associated with non-WRML class
            }

            return mediaType;
        }

        public Context getContext() {
            return Context.this;
        }
    }

    private final class MediaTypeToSchemaIdTransformer extends MediaTypeTransformer<URI> {

        public URI aToB(MediaType aValue) {
            // TODO Auto-generated method stub
            return null;
        }

        public MediaType bToA(URI bValue) {
            // TODO Auto-generated method stub
            return null;
        }

    }

    private final class MediaTypeToStringTransformer extends MediaTypeTransformer<String> {

        public String aToB(MediaType bValue) {

            final StringBuilder sb = new StringBuilder();
            sb.append(bValue.getType().trim()).append('/').append(bValue.getSubtype().trim());

            // TODO: Append params

            return sb.toString();
        }

        public MediaType bToA(String aValue) {

            final Matcher matcher = MEDIA_TYPE_REGEX_PATTERN.matcher(aValue);

            final String type = matcher.group(0);
            final String subtype = matcher.group(1);

            // TODO: Finish and test

            final SortedMap<String, String> parameters = null;
            return createMediaType(type, subtype, parameters);
        }

    }

    private abstract class MediaTypeTransformer<B> implements Transformer<MediaType, B> {

        protected MediaType createMediaType(final String type, final String subtype,
                final SortedMap<String, String> parameters) {

            MediaType mediaType = (MediaType) getContext().instantiateModel(MediaType.class).getStaticInterface();
            mediaType.setFieldValue("type", type);
            mediaType.setFieldValue("subtype", subtype);
            mediaType.setFieldValue("parameters", parameters);

            return mediaType;
        }

        public Context getContext() {
            return Context.this;
        }
    }

}
